on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  spotify-to-readme-job:
    runs-on: ubuntu-latest
    name: Write Spotify songs to readme
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
      - name: Get info from Spotify and write new readme
        id: spotify
        uses: beam41/spotify-listening-svg@main
        with:
          imgHeight: 300
          rawBasePath: https://raw.githubusercontent.com/beam41/beam41/master/
          baseSvgPath: ./base.svg
          token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          clientId: ${{ secrets.SPOTIFY_CLIENT_ID }}
          cliSecret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      - name: Commit file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Spotify data to readme"
      - name: Push change
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
